s=input("Enter ur name :")
c=input("Enter ur college name :")
r=input("Enter ur branch :")
g=input("Enter ur gender :")
a=int(input("Enter ur age :"))
print("NAME :",s)
print("COLLEGE NAME :",c)
print("BRANCH :",r)
print("GENDER :",g)
print("AGE :",a)
